### ISSUE TITLE
Unreachable code?

### ISSUE THREAD

**Issue by frbl** [Vitens/epynet#28]
We were wondering, we found this piece of code and it seems that this specific line is unreachable as both `EN_PIPE` and `EN_RESERVOIR` are `1`, hence if `link_type` equals 1, it will fall through to the first if statement. Also, the reservoir is a node_type, instead of a link type, right?

This is the line (and the next one):
https://github.com/Vitens/epynet/blob/master/epynet/network.py#L152

Best,
Frank

**Comment by frbl** [comment]
Also, with these functions, we receive the following error:

```
Traceback (most recent call last):
  File "src/network.py", line 202, in <module>
    net.ep.ENdeletenode(index)
  File "venv/lib/python3.7/site-packages/epynet/epanet2.py", line 508, in ENdeletenode
    if ierr!=0: raise ENtoolkitError(self, ierr)
epynet.epanet2.ENtoolkitError: Error 251: function call contains invalid parameter code
```

caused by the interaction with the clib https://github.com/Vitens/epynet/blob/master/epynet/network.py#L157

**Comment by AbelHeinsbroek** [comment]
Good catches! 

The first issue is I guess a copy-and-paste related error, that should read EN_PUMP instead of EN_RESERVOIR

The second issue is caused by EPYNET using a development version of the EPANET library which has apparently changed the parameters of that API call.

I'll see if I can find some time to fix this, and write some unit tests to cover node/junction deletion
